PRESETS = {
    "Linha de base": {
        "rainfall_pct": 0,
        "flow_pct": 0,
        "tide_amplitude_pct": 0,
        "salinity_shift_psu": 0,
        "nutrient_load_pct": 0,
        "turbidity_load_pct": 0,
        "point_source_intensity": 0,
    },
    "Chuva intensa": {
        "rainfall_pct": 80,
        "flow_pct": 30,
        "tide_amplitude_pct": 0,
        "salinity_shift_psu": -2,
        "nutrient_load_pct": 20,
        "turbidity_load_pct": 45,
        "point_source_intensity": 10,
    },
    "Estiagem / baixa descarga": {
        "rainfall_pct": -55,
        "flow_pct": -40,
        "tide_amplitude_pct": 10,
        "salinity_shift_psu": 5,
        "nutrient_load_pct": 0,
        "turbidity_load_pct": -15,
        "point_source_intensity": 0,
    },
    "Dragagem / ressuspensão": {
        "rainfall_pct": 0,
        "flow_pct": 0,
        "tide_amplitude_pct": 15,
        "salinity_shift_psu": 0,
        "nutrient_load_pct": 10,
        "turbidity_load_pct": 120,
        "point_source_intensity": 0,
    },
    "Carga de nutrientes": {
        "rainfall_pct": 0,
        "flow_pct": 0,
        "tide_amplitude_pct": 0,
        "salinity_shift_psu": 0,
        "nutrient_load_pct": 100,
        "turbidity_load_pct": 10,
        "point_source_intensity": 0,
    },
    "Lançamento pontual": {
        "rainfall_pct": 0,
        "flow_pct": 0,
        "tide_amplitude_pct": 0,
        "salinity_shift_psu": 0,
        "nutrient_load_pct": 35,
        "turbidity_load_pct": 25,
        "point_source_intensity": 75,
    },
}
